version: '3'
services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3